---
title: "STAT 184 Homework Exercises" 
subtitle: "DataComputing Chapters 1 & 2"
author: "Your Name"
output: html_notebook
---

## Assigned Exercises

- DC Chapter 8 Exercises：8.1-8.3

### Problem 8.1
Construct a graphics frame: ggplot()


Add a layer of glyphs:facet_wrap(),facet_grid()

Set an axis label: geom_histogram(), geom_point()

Divide the frame into facets: geom_segment()

Change the scale for the frame: xlim(), ylab(),scale_y_log10()


### Problem 8.2
```{r}
rm(list = ls())

library(tidyverse)
library(mosaicData)
data("CPS85")
acdata=data("CPS85")
#help("BabyNames")
CPS85 %>%
  head()


```
```{R}
library(esquisse)
CPS85 %>%
ggplot(aes(x=wage,fill=sex)) +
facet_wrap(~married) +
geom_density(alpha = 0.5,xlim=30) 

```
```{R}
library(esquisse)
CPS85 %>%
ggplot(aes(x=age,y=wage,colour=sex)) +
facet_grid(married~.) +
geom_smooth() 


```
```{R}
library(esquisse)
CPS85 %>%
ggplot(aes(x = age, y = wage, colour=sex)) +
  geom_smooth() +
  facet_wrap(~sector) + 
  coord_cartesian(xlim = c(20, 65), ylim = c(0,25))


```

### Problem 8.3
```{r}
CPS85 %>%
ggplot(aes(x = age, y = wage)) +
geom_point()


```
```{r}
CPS85 %>%
ggplot(aes(x = age, y = wage,colour=sex)) +
facet_wrap(married~.)+
geom_point() +
theme(legend.position = "top")

```



```{r}
CPS85 %>%
ggplot(aes(x = age, y = wage,colour=sex)) +
facet_grid(married~.)+
geom_point()+
theme(legend.position = "top")

```
```{r}
CPS85 %>%
ggplot(aes(x = age, y = wage,colour=married)) +
geom_point()+
coord_cartesian( ylim = c(0,30)) +
theme(legend.position = "top")

```
222

